class InterfaceField:
    ID = "id"
    IP = "ip"
    COMMUNITY = "community"
    SYSNAME = "sysname"
    IFINDEX = "ifIndex"
    IFNAME = "ifName"
    IFDESCR = "ifDescr"
    IFALIAS = "ifAlias"
    IFHIGHSPEED = "ifHighSpeed"
    IFOPERSTATUS = "ifOperStatus"
    IFADMINSTATUS = "ifAdminStatus"
    CONSULTED_AT = "consulted_at"



class UserField:
    USERNAME = "username"
    PASSWORD = "password"
    NAME = "name"
    LASTNAME = "lastname"
    STATUS = "status"
    ROLE = "role"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class AssignmentField:
    OLD_INTERFACE_ID = "old_interface_id"
    CURRENT_INTERFACE_ID = "current_interface_id"
    USERNAME = "user_id"
    ASSIGN_BY = "assign_by"
    TYPE_STATUS = "type_status"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class AssignmentCompleteField:
    ID_OLD = "id_old"
    IP_OLD = "ip_old"
    COMMUNITY_OLD = "community_old"
    SYSNAME_OLD = "sysname_old"
    IFINDEX_OLD = "ifIndex_old"
    IFNAME_OLD = "ifName_old"
    IFDESCR_OLD = "ifDescr_old"
    IFALIAS_OLD = "ifAlias_old"
    IFHIGHSPEED_OLD = "ifHighSpeed_old"
    IFOPERSTATUS_OLD = "ifOperStatus_old"
    IFADMINSTATUS_OLD = "ifAdminStatus_old"
    ID_NEW = "id_new"
    IP_NEW = "ip_new"
    COMMUNITY_NEW = "community_new"
    SYSNAME_NEW = "sysname_new"
    IFINDEX_NEW = "ifIndex_new"
    IFNAME_NEW = "ifName_new"
    IFDESCR_NEW = "ifDescr_new"
    IFALIAS_NEW = "ifAlias_new"
    IFHIGHSPEED_NEW = "ifHighSpeed_new"
    IFOPERSTATUS_NEW = "ifOperStatus_new"
    IFADMINSTATUS_NEW = "ifAdminStatus_new"
    USERNAME = "username"
    NAME = "name"
    LASTNAME = "lastname"
    ASSIGN_BY = "assign_by"
    TYPE_STATUS = "type_status"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class StatisticsField:
    TOTAL_PENDING_TODAY = "total_pending_today"
    TOTAL_INSPECTED_TODAY = "total_inspected_today"
    TOTAL_REDISCOVERED_TODAY = "total_rediscovered_today"
    TOTAL_PENDING_MONTH = "total_pending_month"
    TOTAL_INSPECTED_MONTH = "total_inspected_month"
    TOTAL_REDISCOVERED_MONTH = "total_rediscovered_month"
    USERNAME = "username"
    NAME = "name"
    LASTNAME = "lastname"


class ConfigField:
    SNMP = "snmp"
    HOST = "host"
    USER = "user"
    PASSWORD = "password"
    PORT = "port"
    CAN_ASSIGN = "can_assign"
    CAN_RECEIVE_ASSIGNMENT = "can_receive_assignment"
    VIEW_INFORMATION_GLOBAL = "view_information_global"
    NOTIFICATION_CHANGES = "notification_changes"
    ROOT = "root"
    USER = "user"
    SOPORT = "soport"
    ADMIN = "admin"
    IFNAME = "ifName"
    IFDESCR = "ifDescr"
    IFALIAS = "ifAlias"
    IFHIGHSPEED = "ifHighSpeed"
    IFOPERSTATUS = "ifOperStatus"
    IFADMINSTATUS = "ifAdminStatus"


class ChangeField:
    ID_OLD = "id_old"
    IP_OLD = "ip_old"
    COMMUNITY_OLD = "community_old"
    SYSNAME_OLD = "sysname_old"
    IFINDEX_OLD = "ifIndex_old"
    IFNAME_OLD = "ifName_old"
    IFDESCR_OLD = "ifDescr_old"
    IFALIAS_OLD = "ifAlias_old"
    IFHIGHSPEED_OLD = "ifHighSpeed_old"
    IFOPERSTATUS_OLD = "ifOperStatus_old"
    IFADMINSTATUS_OLD = "ifAdminStatus_old"
    ID_NEW = "id_new"
    IP_NEW = "ip_new"
    COMMUNITY_NEW = "community_new"
    SYSNAME_NEW = "sysname_new"
    IFINDEX_NEW = "ifIndex_new"
    IFNAME_NEW = "ifName_new"
    IFDESCR_NEW = "ifDescr_new"
    IFALIAS_NEW = "ifAlias_new"
    IFHIGHSPEED_NEW = "ifHighSpeed_new"
    IFOPERSTATUS_NEW = "ifOperStatus_new"
    IFADMINSTATUS_NEW = "ifAdminStatus_new"
    ASSIGNED = "assigned"


class ChangeAssignField:
    ID_OLD = "id_old"
    IP_OLD = "ip_old"
    COMMUNITY_OLD = "community_old"
    SYSNAME_OLD = "sysname_old"
    IFINDEX_OLD = "ifIndex_old"
    IFNAME_OLD = "ifName_old"
    IFDESCR_OLD = "ifDescr_old"
    IFALIAS_OLD = "ifAlias_old"
    IFHIGHSPEED_OLD = "ifHighSpeed_old"
    IFOPERSTATUS_OLD = "ifOperStatus_old"
    IFADMINSTATUS_OLD = "ifAdminStatus_old"
    ID_NEW = "id_new"
    IP_NEW = "ip_new"
    COMMUNITY_NEW = "community_new"
    SYSNAME_NEW = "sysname_new"
    IFINDEX_NEW = "ifIndex_new"
    IFNAME_NEW = "ifName_new"
    IFDESCR_NEW = "ifDescr_new"
    IFALIAS_NEW = "ifAlias_new"
    IFHIGHSPEED_NEW = "ifHighSpeed_new"
    IFOPERSTATUS_NEW = "ifOperStatus_new"
    IFADMINSTATUS_NEW = "ifAdminStatus_new"
    USERNAME = "username"
    NAME = "name"
    LASTNAME = "lastname"
