CREATE TABLE equipment (
    ip VARCHAR(15) PRIMARY KEY,
    community VARCHAR(30) PRIMARY KEY,
    sysname VARCHAR(30) NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updatedAt TIMESTAMP
);