from controllers.system import SystemController
from controllers.equipment import EquipmentController
from controllers.interface import InterfaceController
from controllers.operator import OperatorController