from controllers.operator import OperatorController
from controllers.equipment import EquipmentController
from controllers.interface import InterfaceController
from controllers.system import SystemController